### ISSUE TITLE
Every listing has the same description

### ISSUE THREAD

**Issue by nnur** [valiahq/Valia-Web#153]

**Comment by dharness** [comment]
@wghozayel there seems to be no title attribute in the DB, possibly I'm missing something. Can you comment on this?

**Comment by wghozayel** [comment]
Hey Dillion,

Yes, I have upgrade the database and am pulling new listings into the new
DB. You can find the connection string in urbania.py. if you have trouble
finding it or have any questions, text me or email me.

519-551-9418

Thanks,

Waseem
