### ISSUE TITLE
Rent/Sell differentiation

### ISSUE THREAD

**Issue by dharness** [valiahq/Valia-Web#168]
The box up to the right on top of the map says “$/month” however there are many results in listings that correspond to a sell. Idem with price range bar.

**Comment by dharness** [comment]
@larryblyth can you clarify what you mean by "Idem with price range bar" ?

**Comment by larryblyth** [comment]
Asking Carlos what he meant. Ignore that last sentence for now. the sell vs buy issue is clear though?

**Comment by dharness** [comment]
@larryblyth Would you like me to remove the "Sell" listings from the results? Or Remove the rent listings from the results, and change the /month to be just $? Or both, with a toggle somewhere.

If both, are rent and sell mutually exclusive? If not, what should the analytics panel label read in the case that both "rent" and "sell" are selected?

**Comment by larryblyth** [comment]
previously, on the first page we had rent and buy as the 'search' buttons next to the text field. That should filter rent vs buy and there should be the same toggle next to the search bar on the top of the second page.

buy and rent will be mutually exclusive

When it is buy, the analytics should just be $

**Comment by dharness** [comment]
Ah, now I remember why we removed this:

https://puu.sh/vKNvY/dfbfb130d4.png

https://puu.sh/vKNxi/6147d1083c.png

https://puu.sh/vKNy8/f3eab3db99.png

**Comment by larryblyth** [comment]
Okay. Can you fix the filter?

**Comment by dharness** [comment]
I'm not sure what you mean. If I add the filter there won't be any listings showing up because everything is null in the DB

**Comment by larryblyth** [comment]
![](http://i.imgur.com/RCRSG0k.jpg)

**Comment by larryblyth** [comment]
Okay I thought we fixed that field in the db. I'll ask Waseem

**Comment by larryblyth** [comment]
Can you add Waseem and tag him so he can see this?

**Comment by dharness** [comment]
Sure. Moving price range discussion here:
https://github.com/valiahq/Valia-Web/issues/174

**Comment by dharness** [comment]
@wghozayel can you have a look at this?

**Comment by wghozayel** [comment]
We only have sell listings in the db right now

**Comment by dharness** [comment]
@larryblyth is this feature essential for whatever your plan is for this mvp? I'd like to move it to post-mvp for the sake of closure

**Comment by larryblyth** [comment]
Yes it is essential - rent is more important than buy. @Waseem can you just add a random few rent listings so that Dylan can test it works.

**Comment by waseem** [comment]
@larryblyth Sure, but I don't know where the database is or how to access it. 😃

**Comment by larryblyth** [comment]
Woops. @Wghozayel

**Comment by wghozayel** [comment]
I have added rent listings to the database. There is a new attribute called forRent. It is currently only available on rental properties and is set to true.
