### ISSUE TITLE
Pins/listings persist when map is dragged s.t they are off screen

### ISSUE THREAD

**Issue by dharness** [valiahq/Valia-Web#171]
For example after a search, the listings re-populate on left but the map doesn't show any pins

**Comment by dharness** [comment]
@larryblyth this seems to work with the cases I tried. Can you provide specific steps to produce?

**Comment by larryblyth** [comment]
@dharness move the map away from where there are pins, and you'll still see listings on the left, even though there are no listings within the map's view.
