### ISSUE TITLE
Price range does not match map

### ISSUE THREAD

**Issue by dharness** [valiahq/Valia-Web#174]
Set price range to $1000

Some items in the map are $1200.

I believe this will be solved by https://github.com/valiahq/Valia-Web/issues/171

but putting it here just in case

**Comment by dharness** [comment]
@larryblyth I don't think it makes sense to have the bounds of the price range match the highest and lowest results in the query. For situations where the number of results is very low, like 2 or 3 the graph would either have gigantic bars to divide the narrow range into meaningful sections or bars with non-useful meaning.

Say, the price range in France is $100 - $105, because there are exactly 2 results with 100$ and $105 price points respectively. The bar graph could be something like 2 giant bars, 100-102.5, 102.5-105 or more bars with very small intervals - say, 50 10cent bars as it appears now.

The first option looks bad, but is useful the second option looks good but is not useful. I think a better option is to do as airbnb does and just have $1000+ or whatever meaningful max ought to apply depending on if the query is rent/sell.

https://puu.sh/vKPoX/332f15e21e.png

**Comment by larryblyth** [comment]
I agree :)
